name: Check types

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  build-n-publish:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install mypy and toshiba-ac
      run: |
        pip install wheel
        pip install mypy==1.11.1
        pip install -e .
    - name: Check types
      run: mypy .
